export const SET_USER = 'SET_USER';
export const SET_IS_USER_LOADING = 'SET_IS_USER_LOADING';
export const SET_IS_USER_COOKIE_LOADING = 'SET_IS_USER_COOKIE_LOADING';
export const SET_USER_ID_TOKEN = 'SET_USER_ID_TOKEN';
